------------- WINDOW FUNCTION II -------------
USE AdventureWorks2019;
GO

SET STATISTICS IO ON;
GO

SET STATISTICS TIME ON;
GO

SELECT --EX01
    SALESORDERID,
    CUSTOMERID,
    SUBTOTAL,
    SUM(SUBTOTAL) OVER() AS TOTAL_SALES,

    SUM(SUBTOTAL) OVER(PARTITION BY CUSTOMERID) AS TOTAL_CUST
FROM Sales.SalesOrderHeader;
GO

-- UTILIZANDO O RECURSO DE FRAMING
SELECT
	SALESORDERID,
	CUSTOMERID,
	SUBTOTAL,

	SUM(SUBTOTAL) OVER (PARTITION BY CUSTOMERID
						ORDER BY ORDERDATE
						ROWS UNBOUNDED PRECEDING) AS TOTAL_ACUMULATE

FROM Sales.SalesOrderHeader;
GO

SELECT 
    CUSTOMERID, 
    SUBTOTAL,
    CAST(SUM(SUBTOTAL) OVER () AS numeric(12,2)) AS TOTAL_SUM,
    SUM(SUBTOTAL) OVER (PARTITION BY CUSTOMERID) AS SUM_CUST,
    CAST(100. * SUM(SUBTOTAL) OVER (PARTITION BY CUSTOMERID) / SUM(SUBTOTAL) OVER () AS decimal(5,3)) AS PCT_CUST
FROM SALES.SALESORDERHEADER;
GO

-- PERCENTAGE BY YEAR
SELECT
	CUSTOMERID,
	SUBTOTAL,
	YEAR(ORDERDATE) AS ORDERYEAR,
	SUM(SUBTOTAL) OVER (PARTITION BY CUSTOMERID) AS TOTAL_CUST,

	CAST(SUM(SUBTOTAL) OVER() AS numeric(12,2)) AS TOTAL,

	CAST(100. * SUM(SUBTOTAL) OVER (PARTITION BY CUSTOMERID) / 
	SUM(SUBTOTAL) OVER(PARTITION BY YEAR(ORDERDATE)) AS decimal(5,2)) AS CUST_PCT_YEAR,

	CAST(SUM(SUBTOTAL) OVER(PARTITION BY YEAR(ORDERDATE)) / 
	SUM(SUBTOTAL) OVER () AS numeric(5,2)) AS PCT_YEAR

FROM Sales.SalesOrderHeader;
GO

SELECT
    CUSTOMERID,
    SUBTOTAL,
    CAST(100. * SUM(SUBTOTAL) / SUM(SUBTOTAL)  OVER(PARTITION BY CUSTOMERID) AS decimal(5,2)) AS PCT_CUST
FROM Sales.SalesOrderHeader
GROUP BY CUSTOMERID, SUBTOTAL;
GO


SELECT DISTINCT

	TERRITORYID,
	SUM(SUBTOTAL) OVER(PARTITION BY TERRITORYID) AS SUMTERRITORY,

	SUM(SUBTOTAL) OVER() AS SUMTOTAL,

	CAST(100.* SUM(SUBTOTAL) OVER(PARTITION BY TERRITORYID) / 
	SUM(SUBTOTAL) OVER() AS numeric(5,2)) AS PCT

FROM Sales.SalesOrderHeader
WHERE TerritoryID BETWEEN 6 AND 9;
GO

SELECT DISTINCT
	TERRITORYID,
	(SELECT SUM(SUBTOTAL)
		FROM Sales.SalesOrderHeader AS T2
		WHERE T2.TerritoryID = T1.TerritoryID) AS TOTAL_BY_TERRITORY,

	(SELECT SUM(SUBTOTAL) 
		FROM Sales.SalesOrderHeader) AS TOTAL,

	CAST(100.*((SELECT SUM(SUBTOTAL) 
		FROM Sales.SalesOrderHeader AS T3
		WHERE T3.TerritoryID = T1.TerritoryID) / 
	(SELECT SUM(SUBTOTAL)
		FROM Sales.SalesOrderHeader))AS numeric(5,2)) AS PCT_TERRITORY

FROM Sales.SalesOrderHeader AS T1
ORDER BY TerritoryID;
GO

--EX4

--EX05 DESTACAR ORDER BY E O FRAMING
SELECT
	SALESORDERID,
	SALESPERSONID,
	SUBTOTAL,

	CAST(100. * SubTotal / SUM(SUBTOTAL) OVER() AS numeric(5,2)) AS PCTALL,
	CAST(100. * SUBTOTAL / SUM(SUBTOTAL) OVER(PARTITION BY SALESPERSONID) AS numeric(5,2)) AS PCTSALESPERSON,

	SUM(SUBTOTAL) OVER(PARTITION BY SALESPERSONID
						ORDER BY SALESPERSONID
						ROWS  UNBOUNDED PRECEDING) AS RUNSELL

FROM Sales.SalesOrderHeader
WHERE SalesPersonID IS NOT NULL;
GO

--EX6
SELECT
	PRODUCTID,
	ORDERQTY,
	SUM(ORDERQTY) OVER (PARTITION BY PRODUCTID
						ORDER BY ORDERQTY 
						ROWS UNBOUNDED PRECEDING) AS RUN_QTD,

	SUM(ORDERQTY) OVER (PARTITION BY PRODUCTID
						ORDER BY ORDERQTY DESC
						ROWS UNBOUNDED PRECEDING) AS ASC_QTD
FROM Sales.SalesOrderDetail
WHERE ProductID = 707;
GO

SELECT
	CUSTOMERID,
	SUBTOTAL,
	SUM(SUBTOTAL) OVER (PARTITION BY CUSTOMERID
						ORDER BY CUSTOMERID
						ROWS UNBOUNDED PRECEDING) AS RUNTOTAL,
	
	SUM(SUBTOTAL) OVER (PARTITION BY CUSTOMERID
						ORDER BY CUSTOMERID
						ROWS BETWEEN CURRENT ROW
						AND 1 FOLLOWING) AS FL_TOTAL,

	SUM(SUBTOTAL) OVER (PARTITION BY CUSTOMERID
						ORDER BY CUSTOMERID
						ROWS BETWEEN CURRENT ROW
						AND 2 FOLLOWING) AS CUST_TOTAL

FROM Sales.SalesOrderHeader;
GO

SELECT --EX6.1
	PRODUCTID,
	CAST(LINETOTAL AS numeric(12,2)) AS LINETOTAL,
	CAST(SUM(LINETOTAL) OVER (PARTITION BY PRODUCTID
							ORDER BY LINETOTAL DESC
							ROWS UNBOUNDED PRECEDING) AS numeric(12,2)) AS RUN_TOTAL,

	CAST(SUM(LINETOTAL) OVER (PARTITION BY PRODUCTID
							ORDER BY LINETOTAL 
							ROWS BETWEEN CURRENT ROW
							AND UNBOUNDED FOLLOWING) AS numeric(12,2)) AS DSC_RUN_TOTAL
FROM Sales.SalesOrderDetail;
GO

--EX6.2
SELECT
	SALESORDERID,
	ORDERQTY,
	MAX(ORDERQTY) OVER (PARTITION BY SALESORDERID
						ORDER BY SALESORDERID
						ROWS BETWEEN 1 PRECEDING
								AND 1 PRECEDING) AS PRVQTY,

	MAX(ORDERQTY) OVER (PARTITION BY SALESORDERID
						ORDER BY SALESORDERID
						ROWS BETWEEN 1 FOLLOWING
								AND 1 FOLLOWING) AS NXTQTY,

	SUM(ORDERQTY) OVER (PARTITION BY SALESORDERID
						ORDER BY SALESORDERID ASC
						ROWS BETWEEN 1 PRECEDING
								AND 1 FOLLOWING) AS SUMQTY
FROM Sales.SalesOrderDetail;
GO


SELECT --EX 6.3
	SALESORDERID,
	CAST(LINETOTAL AS numeric(9,2)) AS LINETOTAL,
	CAST(SUM(LINETOTAL) OVER (PARTITION BY SALESORDERID
							ORDER BY SALESORDERID
							ROWS UNBOUNDED PRECEDING) AS numeric(12,2)) AS SUM_LINETOTAL,
	CAST(SUM(LINETOTAL) OVER (PARTITION BY SALESORDERID
							ORDER BY SALESORDERID
							ROWS BETWEEN 1 PRECEDING
							AND 1 FOLLOWING) AS numeric(12,2)) AS LINETOTAL_SUM,
	CAST(SUM(LINETOTAL) OVER (PARTITION BY SALESORDERID
							ORDER BY SALESORDERID
							ROWS BETWEEN 1 PRECEDING
							AND 2 FOLLOWING) AS numeric(12,2)) AS ROW_SUM
FROM Sales.SalesOrderDetail
WHERE ProductID = 707
ORDER BY SalesOrderID;

WITH CT AS (

	SELECT
		CUSTOMERID,
		CAST(ORDERDATE AS date) AS ORDERDATE,
		SALESORDERID,

		MAX(SALESORDERID) OVER (PARTITION BY CUSTOMERID
							ORDER BY ORDERDATE
							ROWS BETWEEN 1 PRECEDING
							AND 1 PRECEDING) AS PRV_ORDER,

		MAX(SALESORDERID) OVER (PARTITION BY CUSTOMERID
							ORDER BY ORDERDATE
							ROWS BETWEEN 1 FOLLOWING
							AND 1 FOLLOWING) AS NXT_ORDER
FROM Sales.SalesOrderHeader)
SELECT * FROM CT;
GO

SELECT -- ex 6.4
	TERRITORYID,
	CAST(ORDERDATE AS date) AS ORDERDATE,
	MAX(ORDERQTY) OVER (PARTITION BY TERRITORYID
						ORDER BY ORDERDATE
						ROWS BETWEEN 1 PRECEDING
						AND 1 PRECEDING) AS PRVQTY,

	ORDERQTY AS CURQTY,
	
	MAX(ORDERQTY) OVER (PARTITION BY TERRITORYID
						ORDER BY ORDERDATE
						ROWS BETWEEN 1 FOLLOWING
						AND 1 FOLLOWING) AS NXTQTY,
	
	AVG(ORDERQTY) OVER (PARTITION BY TERRITORYID
						ORDER BY ORDERDATE
						ROWS BETWEEN 1 PRECEDING
						AND 1 FOLLOWING) AS AVGQTY
FROM Sales.SalesOrderHeader AS SOH
	INNER JOIN
	Sales.SalesOrderDetail AS SOD
ON SOH.SalesOrderID = SOD.SalesOrderID;

SELECT
	TERRITORYID,
	ORDERDATE,
	ORDERQTY
FROM Sales.SalesOrderHeader AS SOH
	INNER JOIN
	Sales.SalesOrderDetail AS SOD
ON SOH.SalesOrderID = SOD.SalesOrderID
WHERE TerritoryID = 1 AND OrderDate = '20110531'
ORDER BY TerritoryID;

SELECT --6.5
	SALESPERSONID,
	CAST(ORDERDATE AS date) AS ORDERDATE,
	MAX(SUBTOTAL) OVER (PARTITION BY SALESPERSONID
						ORDER BY ORDERDATE, SALESORDERID
						ROWS BETWEEN 1 PRECEDING
						AND 1 PRECEDING) AS PRVTOTAL,
	SUBTOTAL AS CURTOTAL,

	MAX(SUBTOTAL) OVER (PARTITION BY SALESPERSONID
						ORDER BY ORDERDATE, SALESORDERID
						ROWS BETWEEN 1 FOLLOWING
						AND 1 FOLLOWING) AS NXTTOTAL,

	AVG(SUBTOTAL) OVER (PARTITION BY SALESPERSONID
						ORDER BY ORDERDATE, SALESORDERID
						ROWS BETWEEN 1 PRECEDING
						AND 1 FOLLOWING) AS AVGTOTAL
FROM Sales.SalesOrderHeader
WHERE SalesPersonID <> 0;

-- EX9.2
WITH LASTTHREEORDER AS (

SELECT 
	CAST(ORDERDATE AS date) AS ORDERDATE,
	SUM(COUNT(*)) OVER (ORDER BY ORDERDATE
						ROWS BETWEEN 2 PRECEDING
						AND CURRENT ROW) AS NUMORDERLAST3DAYS
FROM Sales.SalesOrderHeader
GROUP BY ORDERDATE
)
SELECT 
	SALESORDERID, CAST(SOD.ORDERDATE AS date) AS ORDERDATE,
	LTO.NUMORDERLAST3DAYS
FROM Sales.SalesOrderHeader AS SOD
	INNER JOIN
	LASTTHREEORDER AS LTO
ON SOD.OrderDate = LTO.ORDERDATE;
GO

WITH PCT_AGG AS(

	SELECT
		CAST(ORDERDATE AS date) AS ORDERDATE,
		SUM(SUM(SUBTOTAL)) OVER ( ORDER BY ORDERDATE
									ROWS BETWEEN 2 PRECEDING
									AND 1 FOLLOWING) AS SUMTOTAL
	FROM Sales.SalesOrderHeader
	GROUP BY ORDERDATE)

SELECT SOH.SALESORDERID, CAST(SOH.ORDERDATE AS date) AS ORDERDATE,
		CAST(100.00 * SOH.SUBTOTAL / PCTA.SUMTOTAL AS numeric(5,2)) AS PCTLASTTHREEDAYS
FROM Sales.SalesOrderHeader AS SOH
	INNER JOIN PCT_AGG AS PCTA
ON SOH.OrderDate = PCTA.ORDERDATE;
GO

-- WINDON FUNCTION CONTANDO PEDIDOS NO DIA
SELECT TOP 10
	COALESCE(SALESPERSONID, 0) AS SALESPERSON,
	CAST(ORDERDATE AS date) AS ORDERDATE,

	COUNT(SALESORDERID) OVER (PARTITION BY SALESPERSONID
								ORDER BY ORDERDATE
								RANGE UNBOUNDED PRECEDING) AS RUNORDER
FROM Sales.SalesOrderHeader
WHERE SalesPersonID = 274;
GO

SELECT TOP (10)
	COALESCE(SALESPERSONID, 0) AS SALESPERSON,
	CAST(ORDERDATE AS date) AS ORDERDATE,
	COUNT(SALESORDERID) OVER (PARTITION BY SALESPERSONID
								ORDER BY ORDERDATE
								ROWS UNBOUNDED PRECEDING) AS RUNORDER
FROM Sales.SalesOrderHeader
WHERE SalesPersonID = 274;
GO

SELECT
	COALESCE(SALESPERSONID, 0) AS SALESPERSON,
	CAST(ORDERDATE AS date) AS ORDERDATE,
	COUNT(SALESORDERID) OVER (PARTITION BY ORDERDATE) AS CNT,
	COUNT(SALESORDERID) OVER (PARTITION BY SALESPERSONID
								ORDER BY ORDERDATE) AS RUNORDER,
	COUNT(SALESORDERID) OVER (PARTITION BY SALESPERSONID
								ORDER BY ORDERDATE
								ROWS UNBOUNDED PRECEDING) AS ROWSORDER,
	SUM(COUNT(SALESORDERID)) OVER (PARTITION BY SALESPERSONID
									ORDER BY ORDERDATE
									ROWS UNBOUNDED PRECEDING) AS SUMORDER
FROM Sales.SalesOrderHeader
WHERE SalesPersonID = 274
GROUP BY SalesPersonID, ORDERDATE, SALESORDERID;
GO

SELECT 
	SALESPERSONID,
	CAST(ORDERDATE AS date) AS ORDERDATE,
	SOD.OrderQty,
	OrderQty - AVG(CASE WHEN YEAR(ORDERDATE) <= DATEADD(YEAR, -8, CURRENT_TIMESTAMP) THEN OrderQty
			END)
	OVER (PARTITION BY SALESPERSONID) AS DIFF
FROM Sales.SalesOrderHeader AS SOH
	INNER JOIN
	Sales.SalesOrderDetail AS SOD
ON SOH.SalesOrderID = SOD.SalesOrderID
WHERE SalesPersonID IS NOT NULL;
GO

-- DISTINCT AGGREGATE --EX8
WITH DIST_COUNT AS (
SELECT
	COALESCE(SALESPERSONID, 0) AS SALESPERSON,
	SALESORDERID,
	CAST(ORDERDATE AS date) AS ORDERDATE,
	CAST(SUBTOTAL AS numeric(12,2)) AS SUBTOTAL,

	CASE
		WHEN ROW_NUMBER() OVER (PARTITION BY SALESPERSONID, CUSTOMERID
								ORDER BY ORDERDATE) = 1 THEN CUSTOMERID
	END AS DIST_CUSTOMER,

-- A COLUNA RWN É PARA MOSTRAR QUE SOMENTE A 'LINHA 1' ESTÁ SELECIONADA.
	ROW_NUMBER() OVER (PARTITION BY SALESPERSONID, CUSTOMERID
						ORDER BY ORDERDATE) AS RWN
FROM Sales.SalesOrderHeader)
SELECT *,
	COUNT(DIST_CUSTOMER) OVER (PARTITION BY SALESPERSON
								ORDER BY ORDERDATE) AS NUM_CUSTS
FROM DIST_COUNT
ORDER BY NUM_CUSTS;
GO

/*

CALCULANDO A QUANTIDADE DISTINTA DE VENDAS
PARA CADA VENDEDOR NAQUELE DIA

*/ 
-- IMG12
WITH DC AS (
	
	SELECT
		COALESCE(SALESPERSONID, 0) AS SALESPERSON,
		CAST(ORDERDATE AS date) AS ORDERDATE,
		CASE 
			WHEN ROW_NUMBER() OVER (PARTITION BY SALESPERSONID, CUSTOMERID
									ORDER BY ORDERDATE) = 1 THEN CUSTOMERID
		END AS DIST_CUST
	FROM Sales.SalesOrderHeader)

SELECT *, 
	SUM(COUNT(DIST_CUST)) OVER (PARTITION BY SALESPERSON
								ORDER BY ORDERDATE) AS NUMCUST
FROM DC
GROUP BY SALESPERSON, ORDERDATE, DIST_CUST;
GO

SELECT
	ProductCategoryID,
	[NAME] AS CATEGORYNAME,
	ROW_NUMBER() OVER(ORDER BY PRODUCTCATEGORYID) AS RN
FROM Production.ProductCategory;
GO

SELECT --EX9
	SALESORDERID,
	SUBTOTAL,
	COUNT(*) OVER (ORDER BY SALESORDERID
					ROWS UNBOUNDED PRECEDING) AS ROWNUN
FROM Sales.SalesOrderHeader;
GO

SELECT -- EX9.1
	SALESORDERID,
	SUBTOTAL,
	ROW_NUMBER() OVER (ORDER BY SALESORDERID, ORDERDATE) AS RN
FROM Sales.SalesOrderHeader;
GO

SELECT
	SALESORDERID,
	SUBTOTAL,
	ROW_NUMBER() OVER () AS ROWN
FROM Sales.SalesOrderHeader;
GO

SELECT -- EX10
	SALESORDERID,
	SUBTOTAL,
	ROW_NUMBER() OVER (ORDER BY 1) AS RNW
FROM Sales.SalesOrderHeader;
GO


-- NEXT VALUE FOR
CREATE SEQUENCE DBO.SEQ1 AS INT MINVALUE 1;
GO

-- É POSSÍVEL CRIAR UMA SEQUENCIA E UTILIZAR NA CONSULTA.
SELECT
	SALESORDERID,
	ORDERDATE,
	SUBTOTAL,
	NEXT VALUE FOR DBO.SEQ1 OVER(ORDER BY ORDERDATE, SALESORDERID) AS SEQ
FROM Sales.SalesOrderHeader;

SELECT
	SALESORDERID,
	ORDERDATE,
	SUBTOTAL,
	ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS ROWNUM
FROM Sales.SalesOrderHeader;

SELECT
	SALESORDERID,
	SUBTOTAL,
	ROW_NUMBER() OVER (ORDER BY 1/0) AS ROWNUM
FROM Sales.SalesOrderHeader;

----- NTILE -----
--PENSE SEMPRE QUE A FUNÇÃO NTILE IRÁ CRIAR BUCKETS DE DADOS COM O RESULTADO DA QUERY
SELECT
	SALESORDERID,
	SUBTOTAL,
	ROW_NUMBER() OVER(ORDER BY SUBTOTAL) AS ROWN,

	NTILE(10) OVER(ORDER BY SUBTOTAL DESC) AS TILE_ROW
FROM Sales.SalesOrderHeader;
GO

--RANK E DENSE_RANK

-- COMPRAS QUE FORAM FEITAS NA MESMA DATA SÃO "EMPATADAS" NO RANK DA FUNÇÃO
-- NÃO ESQUEÇA QUE A ÚLTIMA WF QUE IRÁ DETERMINAR O ORDER BY DAS OUTRAS
SELECT 
	SALESORDERID,
	CAST(ORDERDATE AS date) AS ORDERDATE,
	SUBTOTAL,
	RANK() OVER (ORDER BY ORDERDATE ASC) AS RNKTOTAL,

	ROW_NUMBER() OVER (ORDER BY ORDERDATE ASC) AS RNUMBER,

-- ULTIMO ORDER BY DA WF DEFINE TODO O ORDENAMENTO 
	DENSE_RANK() OVER (ORDER BY ORDERDATE DESC) AS DNRANK
FROM Sales.SalesOrderHeader;
GO

-- CRIANDO UM DESEMPATE
-- ADICIONE UMA COLUNA COM VALORES ÚNICOS (PK)
-- PARA DENSE RANK NÃO FAZ MUITO SENTIDO, A NATUREZA DA FUNÇÃO É EXATAMENTE ESSA
SELECT
	SALESORDERID, --12.1
	ORDERDATE,
	SUBTOTAL,
	RANK() OVER (ORDER BY ORDERDATE, SALESORDERID ASC) AS RNKROW,
	ROW_NUMBER() OVER (ORDER BY ORDERDATE) AS RWNUMBER,
	DENSE_RANK() OVER (ORDER BY ORDERDATE, SALESORDERID) AS DNSRANK
FROM Sales.SalesOrderHeader;

SELECT --EX12.2
	SALESORDERID,
	ORDERDATE,
	CUSTOMERID,
	SUBTOTAL,
	DENSE_RANK() OVER (ORDER BY ORDERDATE DESC) AS DENSE_TOTAL
FROM Sales.SalesOrderHeader;
GO

IF OBJECT_ID('SALES.DENSE_CUSTOMER') IS NOT NULL DROP FUNCTION SALES.DENSE_CUSTOMER;
GO
CREATE OR ALTER FUNCTION SALES.DENSE_CUSTOMER
	(@DNSRANK AS INT) RETURNS TABLE
AS
RETURN
		WITH DNRANK AS (
			SELECT 
				SALESORDERID,
				CAST(ORDERDATE AS DATE) AS ORDERDATE,
				CUSTOMERID,
				TERRITORYID,
				SUBTOTAL,
				DENSE_RANK() OVER (ORDER BY ORDERDATE ASC) AS CUST_RANK
			FROM SALES.SALESORDERHEADER)

	SELECT SalesOrderID, ORDERDATE, CustomerID, TerritoryID, SubTotal, CUST_RANK
	FROM DNRANK
	WHERE CUST_RANK = @DNSRANK;
GO

SELECT CustomerID, SUBTOTAL
FROM Sales.DENSE_CUSTOMER(5);
GO

--- ALTERNATIVA
--- DESACONSELHÁVEL POR SER BEM MAIS LENTA
SELECT 
	SALESORDERID, CAST(ORDERDATE AS date) AS ORDERDATE, SUBTOTAL,

	(SELECT COUNT(*)
	FROM Sales.SalesOrderHeader AS SOH2
	WHERE SOH2.OrderDate > SOH1.ORDERDATE) +1 AS RNK,

	(SELECT COUNT(DISTINCT ORDERDATE)
	FROM Sales.SalesOrderHeader AS SOH2

	WHERE SOH2.OrderDate > SOH1.ORDERDATE) +1 AS DNRK
FROM Sales.SalesOrderHeader AS SOH1;
GO

--- PERCENT_RANK E CUME_DIST ---
/*
PERCENTILE_RANK INDICA A PORCENTAGEM DOS CLIENTES QUE FIZERAM UMA COMPRA ABAIXO DO VALOR CORRENTE
E CUME_DIST INDICA A PORCENTAGEM DOS CLIENTES QUE FIZERAM UMA COMPRA ABAIXO OU COM O MESMO VALOR QUE A COMPRA CORRENTE
*/

SELECT
	COALESCE(SALESPERSONID, 0) AS SALESPERSON,
	CUSTOMERID,
	RANK() OVER (ORDER BY SUBTOTAL) AS RNK,
	CAST(SUBTOTAL AS numeric(12,2)) AS SUBTOTAL,

	CAST(PERCENT_RANK() OVER (PARTITION BY SALESPERSONID
							ORDER BY SUBTOTAL ASC) AS numeric(5,2)) AS PCT_CUST,

	CAST(CUME_DIST() OVER (PARTITION BY SALESPERSONID
							ORDER BY SUBTOTAL) AS numeric(5,2)) AS CDIST_CUST
FROM Sales.SalesOrderHeader
WHERE SalesPersonID <> 0;
GO

SELECT
	COALESCE(SALESPERSONID, 300) AS SALESPERSON,
	COUNT(*) AS NUMORDERS,

	CAST(PERCENT_RANK() OVER (ORDER BY COUNT(*)) AS numeric(5,3)) AS PRCT_ORDER,

	CAST(CUME_DIST() OVER (ORDER BY COUNT(*)) AS numeric(5,3)) AS CMDT_ORDER

FROM Sales.SalesOrderHeader
GROUP BY SalesPersonID;
GO

WITH PROFILE_CUST AS(

	SELECT
		CUSTOMERID,
		COUNT(*) QTDORDER,
		SUM(SUBTOTAL) AS TOTALCUST,
		RANK() OVER (ORDER BY CUSTOMERID) AS RANK_CUST,

		CAST(PERCENT_RANK() OVER(ORDER BY COUNT(*)) AS numeric(5,3)) AS PRCT_CUST,

		CAST(CUME_DIST() OVER(ORDER BY COUNT(*)) AS numeric(5,3)) AS CMT_CUST

	FROM Sales.SalesOrderHeader
	GROUP BY CustomerID)

SELECT * FROM PROFILE_CUST;
GO

------ INVERSE DISTRIBUTION ------
-- EX14

SELECT
	DEPARTMENT, 
	FIRSTNAME,
	LASTNAME,
	RATE,
	
	PERCENTILE_CONT(0.4) WITHIN GROUP (ORDER BY RATE)
							OVER(PARTITION BY DEPARTMENT) AS CONT_RATE,

	PERCENTILE_DISC(0.8) WITHIN GROUP (ORDER BY RATE)
							OVER(PARTITION BY DEPARTMENT) AS DISC_RATE

FROM HumanResources.vEmployeeDepartment AS HED
	INNER JOIN
	HumanResources.EmployeePayHistory AS EPH
ON HED.BusinessEntityID = EPH.BusinessEntityID;
GO


SELECT
	SALESORDERID,
	CUSTOMERID,
	TerritoryID,
	SUBTOTAL,
	PERCENTILE_DISC(1) WITHIN GROUP (ORDER BY SUBTOTAL)
						OVER(PARTITION BY TERRITORYID) AS CUST_PRCTILE,

	PERCENTILE_CONT(0.7) WITHIN GROUP (ORDER BY SUBTOTAL)
						OVER(PARTITION BY TERRITORYID) AS CONT_CUSTOMER
FROM Sales.SalesOrderHeader;
GO


-------- OFFSET FUNCTIONS --------
-- FUNÇÕES DE LAG E LEAD

SELECT
	CUSTOMERID,
	SALESORDERID,
	CAST(ORDERDATE AS date) AS ORDERDATE,
	LAG(SUBTOTAL) OVER (PARTITION BY CUSTOMERID
						ORDER BY ORDERDATE, SALESORDERID) AS PRV_SUBTOTAL,

	LEAD(SUBTOTAL) OVER (PARTITION BY CUSTOMERID
						ORDER BY ORDERDATE, SALESORDERID) AS NXT_SUBTOTAL,

	FIRST_VALUE(SubTotal) OVER (PARTITION BY CUSTOMERID
						ORDER BY ORDERDATE, SALESORDERID) AS FIRST_TOTAL,

	LAST_VALUE(SubTotal) OVER (PARTITION BY CUSTOMERID
						ORDER BY ORDERDATE, SALESORDERID) AS LAST_TOTAL
FROM Sales.SalesOrderHeader;
GO

SELECT
	CUSTOMERID,
	SUBTOTAL,
	LAG(SUBTOTAL) OVER(PARTITION BY CUSTOMERID
							ORDER BY CUSTOMERID) AS PRV_SUBTOTAL
FROM Sales.SalesOrderHeader;

-- EDITANDO OFFSET

SELECT
	CUSTOMERID,
	SALESORDERID,
	SUBTOTAL,
	LAG(SUBTOTAL, 3) OVER (PARTITION BY CUSTOMERID
							ORDER BY ORDERDATE, SALESORDERID) AS PRV_TOTAL
FROM Sales.SalesOrderHeader;


