version: '3.8'

services:
  spark-master:
    container_name: sparkmaster
    build: .
    image: sparkimage
    entrypoint: ['./entrypoint.sh', 'master']
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - /mnt/d/linux/projetosestudos/spark/dados:/opt/spark/data
      - /mnt/d/linux/projetosestudos/spark/jobs:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
    env_file:
      - .env.spark
    ports:
      - '9090:8080'
      - '7077:7077'


  spark-history-server:
    container_name: sparkhistory
    image: sparkimage
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - spark-logs:/opt/spark/spark-events
    ports:
      - '18080:18080'

  spark-worker:
    image: sparkimage
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - /mnt/d/linux/projetosestudos/spark/dados:/opt/spark/data
      - /mnt/d/linux/projetosestudos/spark/jobs:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events

volumes:
  spark-logs:
